logging:
    level:
        com:
            ysmull:
                easemall: debug
        jdbc:
            audit: off
            resultset: off
#            sqlonly: off
            sqltiming: off
        net:
            sf:
                log4jdbc: debug
        org:
            springframework:
                transaction:
                    interceptor: TRACE
#                jdbc:
#                    core:
#                      JdbcTemplate: debug
#                      StatementCreatorUtils: TRACE
server:
    compression:
        enabled: true
        mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/javascript
        min-response-size: 2048
    error:
        whitelabel:
            enabled: false
    port: 8181

spring:
    application:
        name: EaseMall
    datasource:
        continue-on-error: false
        hikari:
            maximum-pool-size: 10
            driver-class-name: net.sf.log4jdbc.DriverSpy
            jdbc-url: jdbc:log4jdbc:hsqldb:mem:testdb
#            jdbc-url: jdbc:log4jdbc:hsqldb:file:./db/ease;create=true;user=mys;password=123;
#        username: mys
#        password: 123
#            jdbc-url: jdbc:log4jdbc:derby:memory:easeShopdb;create=true
#            auto-commit: false
#            transaction-isolation: TRANSACTION_SERIALIZABLE
    servlet:
      multipart:
        enabled: true
        resolve-lazily: true
        max-file-size: 1MB
    cache:
      caffeine:
        spec: maximumSize=50,expireAfterWrite=60s
      cache-names: userCache