logging:
    level:
        com:
            ysmull:
                easeshop: debug
        jdbc:
            audit: off
            resultset: off
#            sqlonly: off
            sqltiming: off
        net:
            sf:
                log4jdbc: debug
        org:
            springframework:
                transaction:
                    interceptor: TRACE
server:
    compression:
        enabled: true
        mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/javascript
        min-response-size: 2048
    error:
        whitelabel:
            enabled: false
    port: 8181
    undertow:
        direct-buffers: true
        io-threads: 30
        worker-threads: 30
        buffer-size: 200
#        accesslog:
#            dir: ~
#            enabled: true
#            pattern: common
#            prefix: access_log.
#            rotate: true
#            suffix: log
spring:
    application:
        name: easeShop
    datasource:
        continue-on-error: false
        hikari:
            maximum-pool-size: 10
            driver-class-name: net.sf.log4jdbc.DriverSpy
            jdbc-url: jdbc:log4jdbc:hsqldb:file:./db/ease;create=true;user=mys;password=123;
        username: mys
        password: 123
#            jdbc-url: jdbc:log4jdbc:derby:memory:easeShopdb;create=true
#            auto-commit: false
#            transaction-isolation: TRANSACTION_SERIALIZABLE
    servlet:
      multipart:
        enabled: true
        resolve-lazily: true
        max-file-size: 1MB
    cache:
      caffeine:
        spec: maximumSize=50,expireAfterWrite=60s
      cache-names: userCache

#    resources:
#      chain:
#        gzipped: true
#        enabled: true
#        cache: true
#        strategy:
#          content:
#            enabled: true
#log4jdbc.spylogdelegator.name=net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
#logging.level.org.springframework.web=debug
#logging.level.org.springframework.jdbc.core.JdbcTemplate=debug
#logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE
#spring.datasource.driver-class-name=org.apache.derby.jdbc.EmbeddedDriver
#spring.datasource.initialization-mode=embedded
#server.undertow.buffer-size=